services:
  user-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    networks:
      - chatnet

  chat-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: chat-service/Dockerfile
    container_name: chat-service
    ports:
      - "8081:8080"
    networks:
      - chatnet

networks:
  chatnet:
    external:
      name: foxchatnet