services:
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: fox-user
      POSTGRES_PASSWORD: Pass123
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - foxchatnet

  postgres-chat:
    image: postgres:15
    container_name: postgres-chat
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: fox-user
      POSTGRES_PASSWORD: Pass123
    ports:
      - "5434:5432"
    volumes:
      - postgres_chat_data:/var/lib/postgresql/data
    networks:
      - foxchatnet

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_CFG_LISTENERS: CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    ports:
      - "9092:9092"
    networks:
      - foxchatnet

networks:
  foxchatnet:
    name: foxchatnet

volumes:
  postgres_user_data:
  postgres_chat_data: