server:
  servlet:
    context-path: /chat-api/v1/user

spring:
  application:
    name: user-service

  datasource:
    username: fox-user
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres-user:5432/users_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 #1 hour in milliseconds

