server:
  servlet:
    context-path: /chat-api

spring:
  application:
    name: chat-service

  kafka:
    bootstrap-servers: kafka:29092
    client-id: chat-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1

      topic:
        sent: message-sent

  datasource:
    username: fox-user
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres-chat:5432/chat_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

